export const CURRICULUM = [
  {
    id: 'unit-1',
    title: 'Hello Python',
    description: 'Your first steps into Python',
    icon: '🐣',
    color: '#a78bfa',
    lessons: [
      {
        id: 'u1-l1',
        title: 'Your First Print',
        xpReward: 20,
        intro: {
          title: 'Say hello to the world 🌍',
          summary: 'Every programmer starts here. The print() function is how Python talks to you — it displays text on the screen.',
          concepts: [
            { label: 'Basic print', code: 'print("Hello, World!")', output: 'Hello, World!' },
            { label: 'Print a number', code: 'print(42)', output: '42' },
            { label: 'Print multiple things', code: 'print("I am", 25, "years old")', output: 'I am 25 years old' },
          ],
          tip: '💡 The text inside quotes is called a string. Quotes tell Python "this is text, not code."',
        },
        summary: {
          title: 'print() — Your first Python tool',
          points: [
            'print() displays output to the screen',
            'Text (strings) must be wrapped in quotes: "hello" or \'hello\'',
            'Python is case-sensitive — print() works, Print() does not',
            'You can print numbers without quotes: print(42)',
            'Print multiple values separated by commas: print("hi", name)',
          ],
          cheatsheet: [
            { code: 'print("Hello!")', desc: 'Print text' },
            { code: 'print(42)', desc: 'Print a number' },
            { code: 'print("Hi", "there")', desc: 'Print multiple values' },
          ],
        },
        exercises: [
          {
            id: 'u1-l1-e1',
            type: 'multiple_choice',
            teach: {
              title: 'How print() works',
              explanation: 'print() is a built-in Python function. You put what you want to display inside the parentheses. If it\'s text, wrap it in quotes.',
              example: { code: 'print("Hello, World!")', output: 'Hello, World!' },
              highlight: 'The quotes are part of the syntax — they tell Python this is text. But they don\'t appear in the output!',
            },
            question: 'What does this code output?\n\nprint("Hello, World!")',
            options: ['Hello, World!', 'print Hello, World!', 'Error', '"Hello, World!"'],
            correct: 0,
            explanation: 'print() displays whatever is inside the parentheses. The quotes tell Python it\'s text, but they don\'t appear in the output.',
          },
          {
            id: 'u1-l1-e2',
            type: 'fill_blank',
            teach: {
              title: 'The print function name',
              explanation: 'In Python, functions have names. The function that displays output is called print — all lowercase.',
              example: { code: 'print("Python is cool!")', output: 'Python is cool!' },
              highlight: 'Always lowercase: print. Never Print, PRINT, or printf.',
            },
            question: 'Complete the code to print "Python rocks!"',
            code: '___("Python rocks!")',
            correct: 'print',
            explanation: 'print() is the function used to display output in Python.',
          },
          {
            id: 'u1-l1-e3',
            type: 'multiple_choice',
            teach: {
              title: 'Strings need quotes',
              explanation: 'Text in Python is called a "string". Strings MUST be wrapped in quotes. Without quotes, Python thinks you\'re referring to a variable.',
              example: { code: 'print("Hello")  # correct\nprint(Hello)   # error!', output: 'Hello\nNameError!' },
              highlight: 'Use either "double" or \'single\' quotes — both work the same way.',
            },
            question: 'Which of these will print the word Hello?',
            options: ['print(Hello)', 'print("Hello")', 'Print("Hello")', 'echo("Hello")'],
            correct: 1,
            explanation: 'Text (strings) must be wrapped in quotes. Also, Python is case-sensitive — print() is lowercase.',
          },
          {
            id: 'u1-l1-e4',
            type: 'true_false',
            teach: {
              title: 'Python is case-sensitive',
              explanation: 'Python treats uppercase and lowercase letters as completely different. print() is a built-in function, but Print() or PRINT() don\'t exist.',
              example: { code: 'print("hi")   # works\nPrint("hi")   # NameError', output: 'hi\nError!' },
              highlight: 'This applies to everything in Python — variable names, function names, keywords.',
            },
            question: 'Python is case-sensitive, so print() and Print() are the same thing.',
            correct: false,
            explanation: 'Python IS case-sensitive. print() works, but Print() would give you a NameError.',
          },
          {
            id: 'u1-l1-e5',
            type: 'spot_bug',
            teach: {
              title: 'Spotting common mistakes',
              explanation: 'One of the most common beginner mistakes is capitalizing Python\'s built-in functions.',
              example: { code: '# Bug:\nPrint("Welcome")\n\n# Fixed:\nprint("Welcome")', output: 'Error!\nWelcome' },
              highlight: 'When you see a NameError, always check if you accidentally capitalized something.',
            },
            question: 'Find the bug in this code:\n\nPrint("Welcome to Python")',
            options: ['Print should be print', 'Missing semicolon', 'Wrong quotes', 'No bug'],
            correct: 0,
            explanation: 'The built-in function is print() with a lowercase p. Python is case-sensitive!',
          },
        ],
      },
      {
        id: 'u1-l2',
        title: 'Variables',
        xpReward: 20,
        intro: {
          title: 'Storing information 📦',
          summary: 'Variables are like labeled boxes. You put a value in a box, give it a name, and then use that name whenever you need the value.',
          concepts: [
            { label: 'Store a number', code: 'age = 25', output: '(stores 25 in "age")' },
            { label: 'Store text', code: 'name = "Alex"', output: '(stores "Alex" in "name")' },
            { label: 'Use a variable', code: 'name = "Alex"\nprint(name)', output: 'Alex' },
          ],
          tip: '💡 Think of a variable like a sticky note — you write a label on it, then stick any value you want.',
        },
        summary: {
          title: 'Variables — Named boxes for your data',
          points: [
            'Variables store values using the = sign',
            'The variable name goes on the LEFT of =',
            'Names must start with a letter or underscore, not a number',
            'Names are case-sensitive: name and Name are different',
            'You can reassign a variable anytime',
          ],
          cheatsheet: [
            { code: 'x = 10', desc: 'Store a number' },
            { code: 'name = "Alex"', desc: 'Store text' },
            { code: 'print(name)', desc: 'Use a variable' },
          ],
        },
        exercises: [
          {
            id: 'u1-l2-e1',
            type: 'multiple_choice',
            teach: {
              title: 'Numbers vs strings',
              explanation: 'x = 42 (no quotes) stores the NUMBER 42. x = "42" (with quotes) stores the TEXT "42". They look similar but behave differently!',
              example: { code: 'x = 42       # number\ny = "42"     # text\nprint(x + 1) # 43\nprint(y + 1) # Error!', output: '43\nTypeError!' },
              highlight: 'No quotes = number you can do math with. Quotes = text.',
            },
            question: 'What is stored in x after this code runs?\n\nx = 42',
            options: ['The text "42"', 'The number 42', 'Nothing', 'An error'],
            correct: 1,
            explanation: 'When you write x = 42 without quotes, Python stores the number 42 (an integer).',
          },
          {
            id: 'u1-l2-e2',
            type: 'fill_blank',
            teach: {
              title: 'Variable assignment syntax',
              explanation: 'To create a variable: write the name, then =, then the value. Name on LEFT, value on RIGHT.',
              example: { code: 'name = "Alex"\nage = 20\ncity = "New York"', output: '(3 variables created)' },
              highlight: 'Read = as "gets" not "equals": name gets "Alex".',
            },
            question: 'Create a variable called name and store "Alex" in it.',
            code: '___ = "Alex"',
            correct: 'name',
            explanation: 'Variable names go on the left of =, and the value goes on the right.',
          },
          {
            id: 'u1-l2-e3',
            type: 'output_prediction',
            teach: {
              title: 'Printing variables',
              explanation: 'When you print a variable, Python displays its VALUE — not the variable name.',
              example: { code: 'city = "Tokyo"\nprint(city)\nprint("city")', output: 'Tokyo\ncity' },
              highlight: 'print(city) shows the VALUE. print("city") shows the TEXT. No quotes = use the variable!',
            },
            question: 'What will this print?\n\nage = 25\nprint(age)',
            options: ['age', '25', '"25"', 'Error'],
            correct: 1,
            explanation: 'print(age) prints the VALUE stored in age, which is 25, not the word "age".',
          },
          {
            id: 'u1-l2-e4',
            type: 'true_false',
            teach: {
              title: 'Variables can be reassigned',
              explanation: 'You can change what\'s stored in a variable at any time — just assign a new value.',
              example: { code: 'score = 0\nprint(score)  # 0\nscore = 10\nprint(score)  # 10', output: '0\n10' },
              highlight: 'score = score + 5 means: take current value, add 5, store back.',
            },
            question: 'You can change the value of a variable after you create it.',
            correct: true,
            explanation: 'Variables can be reassigned anytime. That\'s what makes them "variable"!',
          },
          {
            id: 'u1-l2-e5',
            type: 'spot_bug',
            teach: {
              title: 'Valid variable names',
              explanation: 'Variable names must start with a letter or underscore. They cannot start with a number.',
              example: { code: 'name = "Alex"   # valid\n_score = 10     # valid\n2name = "Alex"  # INVALID', output: 'OK\nOK\nSyntaxError!' },
              highlight: 'Starting with a number is the most common naming mistake.',
            },
            question: 'Find the bug:\n\n2name = "Alex"\nprint(2name)',
            options: ['Variable names cannot start with a number', 'Missing quotes around Alex', 'print is spelled wrong', 'No bug'],
            correct: 0,
            explanation: 'Variable names must start with a letter or underscore, never a number.',
          },
        ],
      },
      {
        id: 'u1-l3',
        title: 'Basic Math',
        xpReward: 20,
        intro: {
          title: 'Python as a calculator 🔢',
          summary: 'Python can do all kinds of math. It follows the correct order of operations (PEMDAS) and has some special operators you might not know.',
          concepts: [
            { label: 'Basic operators', code: 'print(10 + 3)  # 13\nprint(10 - 3)  # 7\nprint(10 * 3)  # 30\nprint(10 / 3)  # 3.333', output: '13\n7\n30\n3.333...' },
            { label: 'Special operators', code: 'print(10 // 3) # 3\nprint(10 % 3)  # 1\nprint(2 ** 3)  # 8', output: '3\n1\n8' },
          ],
          tip: '💡 Python follows PEMDAS — use parentheses to control order of operations.',
        },
        summary: {
          title: 'Math operators in Python',
          points: [
            '+ - * / are the basic arithmetic operators',
            '// is floor division — divides and rounds DOWN',
            '% is modulo — gives the remainder after division',
            '** is the power operator (2 ** 3 = 8)',
            'Python follows order of operations — use () to override',
          ],
          cheatsheet: [
            { code: '10 + 3  → 13', desc: 'Addition' },
            { code: '10 // 3 → 3', desc: 'Floor division' },
            { code: '10 % 3  → 1', desc: 'Modulo (remainder)' },
            { code: '2 ** 3  → 8', desc: 'Power' },
          ],
        },
        exercises: [
          {
            id: 'u1-l3-e1',
            type: 'output_prediction',
            teach: {
              title: 'Math inside print()',
              explanation: 'You can put math expressions directly inside print(). Python evaluates the math first, then displays the result.',
              example: { code: 'print(5 + 3)    # 8\nprint(10 - 4)   # 6\nprint(3 * 7)    # 21', output: '8\n6\n21' },
              highlight: 'Python calculates first — you see the answer, not the expression.',
            },
            question: 'What will this print?\n\nprint(10 + 3)',
            options: ['10 + 3', '103', '13', 'Error'],
            correct: 2,
            explanation: 'Python evaluates the math inside print() first, then displays the result.',
          },
          {
            id: 'u1-l3-e2',
            type: 'multiple_choice',
            teach: {
              title: 'The power operator **',
              explanation: '** raises a number to a power. It\'s Python\'s exponent operator.',
              example: { code: 'print(2 ** 3)   # 8\nprint(5 ** 2)   # 25\nprint(10 ** 0)  # 1', output: '8\n25\n1' },
              highlight: 'Don\'t confuse ** with * (multiply). 2 * 3 = 6, but 2 ** 3 = 8.',
            },
            question: 'What does ** mean in Python?',
            options: ['Multiply', 'Power/Exponent', 'Comment', 'String repeat'],
            correct: 1,
            explanation: '** is the power operator. So 2 ** 3 means 2 to the power of 3, which is 8.',
          },
          {
            id: 'u1-l3-e3',
            type: 'output_prediction',
            teach: {
              title: 'Floor division //',
              explanation: '// divides and rounds the result DOWN to the nearest whole number.',
              example: { code: 'print(10 // 3)  # 3 (not 3.33)\nprint(7 // 2)   # 3 (not 3.5)', output: '3\n3' },
              highlight: '// always rounds DOWN. 7 // 2 = 3, not 4.',
            },
            question: 'What will this print?\n\nprint(10 // 3)',
            options: ['3.333...', '3', '4', '1'],
            correct: 1,
            explanation: '// is floor division — it divides and rounds DOWN to the nearest whole number.',
          },
          {
            id: 'u1-l3-e4',
            type: 'fill_blank',
            teach: {
              title: 'The modulo operator %',
              explanation: '% gives you the REMAINDER after division. If x % 2 == 0, the number is even!',
              example: { code: 'print(10 % 3)  # 1\nprint(10 % 2)  # 0 (even!)\nprint(7 % 4)   # 3', output: '1\n0\n3' },
              highlight: 'x % 2 == 0 means even. x % 2 == 1 means odd.',
            },
            question: 'What operator gives you the remainder of a division?',
            code: 'print(10 ___ 3)  # should print 1',
            correct: '%',
            explanation: '% is the modulo operator. 10 % 3 = 1 because 10 divided by 3 is 3 remainder 1.',
          },
          {
            id: 'u1-l3-e5',
            type: 'true_false',
            teach: {
              title: '/ vs // — a subtle difference',
              explanation: 'Regular / always returns a float. Floor division // returns an integer.',
              example: { code: 'print(10 / 2)   # 5.0 float\nprint(10 // 2)  # 5   int', output: '5.0\n5' },
              highlight: '5.0 and 5 look similar but are different types.',
            },
            question: '10 / 2 gives the same result as 10 // 2 in Python.',
            correct: false,
            explanation: '10 / 2 gives 5.0 (a float), while 10 // 2 gives 5 (an integer).',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-2',
    title: 'Data Types',
    description: 'Strings, numbers, and booleans',
    icon: '🔢',
    color: '#34d399',
    lessons: [
      {
        id: 'u2-l1',
        title: 'Strings',
        xpReward: 20,
        intro: {
          title: 'Text in Python 📝',
          summary: 'A string is any sequence of characters. They\'re one of the most used data types in Python.',
          concepts: [
            { label: 'Create strings', code: 'name = "Alice"\ngreeting = \'Hello!\'', output: '(2 strings)' },
            { label: 'String operations', code: 'print("Hi" + " there")\nprint("ha" * 3)\nprint(len("Python"))', output: 'Hi there\nhahaha\n6' },
          ],
          tip: '💡 Strings are immutable — you can\'t change individual characters, but you can create new strings.',
        },
        summary: {
          title: 'Strings — Working with text',
          points: [
            'Strings are text wrapped in quotes',
            'len() counts the number of characters',
            '+ joins strings together (concatenation)',
            '* repeats a string: "ha" * 3 = "hahaha"',
            'Indexing starts at 0: "Python"[0] = "P"',
          ],
          cheatsheet: [
            { code: 'len("hello")  → 5', desc: 'String length' },
            { code: '"Hi" + " you"', desc: 'Concatenation' },
            { code: '"ha" * 3  → "hahaha"', desc: 'Repetition' },
            { code: '"Python"[0]  → "P"', desc: 'Indexing' },
          ],
        },
        exercises: [
          {
            id: 'u2-l1-e1',
            type: 'multiple_choice',
            teach: {
              title: 'The len() function',
              explanation: 'len() counts the number of characters in a string — including spaces.',
              example: { code: 'print(len("Python"))  # 6\nprint(len("a b"))    # 3', output: '6\n3' },
              highlight: 'Spaces count as characters!',
            },
            question: 'What does len("Python") return?',
            options: ['5', '6', '7', 'Error'],
            correct: 1,
            explanation: 'len() counts every character. "Python" has 6 characters: P-y-t-h-o-n.',
          },
          {
            id: 'u2-l1-e2',
            type: 'output_prediction',
            teach: {
              title: 'String methods',
              explanation: 'Strings come with built-in methods you call using dot notation.',
              example: { code: 'msg = "hello"\nprint(msg.upper())\nprint(msg.capitalize())', output: 'HELLO\nHello' },
              highlight: 'Methods return a NEW string — they don\'t change the original.',
            },
            question: 'What will this print?\n\nname = "Alex"\nprint(name.upper())',
            options: ['alex', 'ALEX', 'Alex', 'Error'],
            correct: 1,
            explanation: '.upper() converts all characters to uppercase.',
          },
          {
            id: 'u2-l1-e3',
            type: 'fill_blank',
            teach: {
              title: 'Joining strings with +',
              explanation: 'The + operator joins two strings together end-to-end (concatenation).',
              example: { code: 'print("Hello" + " World")', output: 'Hello World' },
              highlight: 'You need to add spaces manually: "Hello"+"World" = "HelloWorld".',
            },
            question: 'Join two strings together:',
            code: 'print("Hello" ___ " World")',
            correct: '+',
            explanation: 'The + operator joins (concatenates) strings together.',
          },
          {
            id: 'u2-l1-e4',
            type: 'output_prediction',
            teach: {
              title: 'String repetition with *',
              explanation: 'You can repeat a string by multiplying it with a number.',
              example: { code: 'print("-" * 10)\nprint("hi " * 2)', output: '----------\nhi hi ' },
              highlight: 'Great trick: print("-" * 30) creates a divider line!',
            },
            question: 'What will this print?\n\nprint("ha" * 3)',
            options: ['ha ha ha', 'hahaha', 'Error', '3'],
            correct: 1,
            explanation: 'Multiplying a string by a number repeats it. "ha" * 3 = "hahaha".',
          },
          {
            id: 'u2-l1-e5',
            type: 'multiple_choice',
            teach: {
              title: 'String indexing',
              explanation: 'Each character has an index starting at 0. Use square brackets to access it.',
              example: { code: 'word = "Python"\nprint(word[0])  # P\nprint(word[-1]) # n (last!)', output: 'P\nn' },
              highlight: 'Zero-based indexing: first item = index 0!',
            },
            question: 'How do you get just the first character of a string?\n\nword = "Python"',
            options: ['word[1]', 'word[0]', 'word.first()', 'word(-1)'],
            correct: 1,
            explanation: 'Python uses zero-based indexing. The first character is at index 0.',
          },
        ],
      },
      {
        id: 'u2-l2',
        title: 'Numbers',
        xpReward: 20,
        intro: {
          title: 'Integers and floats 🔢',
          summary: 'Python has two main number types: integers (whole) and floats (decimals). Knowing the difference prevents bugs.',
          concepts: [
            { label: 'Types', code: 'x = 5      # int\ny = 5.0    # float', output: "(int vs float)" },
            { label: 'Conversion', code: 'print(int(3.9))    # 3\nprint(float(5))    # 5.0\nprint(str(42))     # "42"', output: '3\n5.0\n42' },
          ],
          tip: '💡 When you mix int and float in math, Python always returns a float.',
        },
        summary: {
          title: 'Numbers — int and float',
          points: [
            'int = whole numbers (5, -3, 0)',
            'float = decimal numbers (3.14, 2.0)',
            'int() converts to integer — TRUNCATES, does not round',
            'float() converts to float',
            'str() converts a number to a string',
          ],
          cheatsheet: [
            { code: 'int(3.9)  → 3', desc: 'Truncates to int' },
            { code: 'float(5)  → 5.0', desc: 'Convert to float' },
            { code: 'str(42)   → "42"', desc: 'Convert to string' },
          ],
        },
        exercises: [
          {
            id: 'u2-l2-e1',
            type: 'multiple_choice',
            teach: {
              title: 'int vs float',
              explanation: 'int is for whole numbers, float is for numbers with a decimal point.',
              example: { code: 'a = 5      # int\nb = 5.0    # float', output: '(different types, same value)' },
              highlight: '5 and 5.0 have the same value but different types.',
            },
            question: 'What type is the value 3.14?',
            options: ['int', 'float', 'string', 'number'],
            correct: 1,
            explanation: 'Numbers with decimal points are floats. Whole numbers are ints.',
          },
          {
            id: 'u2-l2-e2',
            type: 'output_prediction',
            teach: {
              title: 'int() truncates, not rounds',
              explanation: 'int() cuts off the decimal — it doesn\'t round. 3.9 becomes 3.',
              example: { code: 'print(int(3.1))  # 3\nprint(int(3.9))  # 3 (NOT 4!)', output: '3\n3' },
              highlight: 'Use round() if you want rounding. int() always chops.',
            },
            question: 'What will this print?\n\nprint(int(3.9))',
            options: ['3.9', '4', '3', 'Error'],
            correct: 2,
            explanation: 'int() truncates (chops off) the decimal — it does NOT round.',
          },
          {
            id: 'u2-l2-e3',
            type: 'fill_blank',
            teach: {
              title: 'Converting string to int',
              explanation: 'Numbers from user input come as strings. Use int() to convert them for math.',
              example: { code: 'age_text = "25"\nage_num = int("25")\nprint(age_num + 1)  # 26', output: '26' },
              highlight: 'int("25") works. int("hello") crashes.',
            },
            question: 'Convert the string "42" to an integer:',
            code: 'number = ___(\"42\")',
            correct: 'int',
            explanation: 'int() converts a string to an integer.',
          },
          {
            id: 'u2-l2-e4',
            type: 'true_false',
            teach: {
              title: 'You can\'t mix types in math',
              explanation: 'Python won\'t let you add a number and a string — convert first.',
              example: { code: '5 + "5"        # TypeError!\nint("5") + 5   # 10\nstr(5) + "5"   # "55"', output: 'Error!\n10\n55' },
              highlight: 'Always make sure you\'re working with the same type.',
            },
            question: 'In Python, you can add a number and a string directly: 5 + "5"',
            correct: false,
            explanation: 'This throws a TypeError! Convert to the same type first.',
          },
          {
            id: 'u2-l2-e5',
            type: 'spot_bug',
            teach: {
              title: 'String vs number bug',
              explanation: 'If a number is in quotes, it\'s a string — you can\'t do math with it directly.',
              example: { code: '# Bug:\nage = "25"\nnext = age + 1  # TypeError!\n\n# Fixed:\nage = int("25")\nnext = age + 1  # 26', output: 'TypeError!\n26' },
              highlight: 'TypeError: can only concatenate str — you have a type mismatch.',
            },
            question: 'Find the bug:\n\nage = "25"\nnext_year = age + 1\nprint(next_year)',
            options: ['age is a string, not a number', 'print is missing quotes', 'next_year is reserved', 'No bug'],
            correct: 0,
            explanation: 'age is stored as a string "25". Use int(age) + 1 to fix it.',
          },
        ],
      },
      {
        id: 'u2-l3',
        title: 'Booleans',
        xpReward: 20,
        intro: {
          title: 'True or False 🟢🔴',
          summary: 'Booleans are the simplest data type — only True or False. They\'re the foundation of all decision-making in code.',
          concepts: [
            { label: 'Comparisons', code: 'print(5 > 3)   # True\nprint(5 == 5)  # True\nprint(5 != 3)  # True', output: 'True\nTrue\nTrue' },
            { label: 'Truthy/Falsy', code: 'print(bool(1))    # True\nprint(bool(0))    # False\nprint(bool("hi")) # True\nprint(bool(""))   # False', output: 'True\nFalse\nTrue\nFalse' },
          ],
          tip: '💡 0, empty strings, and None are "falsy". Everything else is "truthy".',
        },
        summary: {
          title: 'Booleans — True and False',
          points: [
            'Only two values: True and False (capitalized!)',
            'Comparison operators return booleans',
            '== checks equality, = assigns (common mistake!)',
            'bool(0) = False, bool(1) = True',
            'Empty strings, 0, and None are "falsy"',
          ],
          cheatsheet: [
            { code: '5 > 3   → True', desc: 'Greater than' },
            { code: '5 == 5  → True', desc: 'Equal to' },
            { code: '5 != 3  → True', desc: 'Not equal' },
            { code: 'bool(0) → False', desc: 'Falsy value' },
          ],
        },
        exercises: [
          {
            id: 'u2-l3-e1',
            type: 'multiple_choice',
            teach: {
              title: 'Boolean values',
              explanation: 'Python\'s booleans are True and False — always capitalized.',
              example: { code: 'x = True\nprint(type(x))  # bool', output: "<class 'bool'>" },
              highlight: 'true (lowercase) doesn\'t work! Must be True.',
            },
            question: 'What are the only two boolean values in Python?',
            options: ['yes/no', 'True/False', '1/0', 'on/off'],
            correct: 1,
            explanation: 'Python booleans are True and False — capitalized exactly like that.',
          },
          {
            id: 'u2-l3-e2',
            type: 'output_prediction',
            teach: {
              title: 'Comparison operators',
              explanation: 'Comparison operators compare values and return True or False.',
              example: { code: 'print(10 > 5)   # True\nprint(10 < 5)   # False\nprint(10 >= 10) # True', output: 'True\nFalse\nTrue' },
              highlight: '>= means "greater than OR equal to".',
            },
            question: 'What will this print?\n\nprint(10 > 5)',
            options: ['10 > 5', 'True', 'False', 'Error'],
            correct: 1,
            explanation: '10 > 5 is a comparison that evaluates to True.',
          },
          {
            id: 'u2-l3-e3',
            type: 'output_prediction',
            teach: {
              title: '== vs = (critical!)',
              explanation: '= assigns a value. == compares values. This is one of the most common mistakes!',
              example: { code: 'x = 5          # assignment\nprint(x == 5)  # True\nprint(5 == 5.0) # True (same value!)', output: 'True\nTrue' },
              highlight: 'Always use == for comparisons, never =.',
            },
            question: 'What will this print?\n\nprint(5 == 5.0)',
            options: ['True', 'False', 'Error', 'Maybe'],
            correct: 0,
            explanation: '== checks value equality. 5 and 5.0 have the same value, so True.',
          },
          {
            id: 'u2-l3-e4',
            type: 'fill_blank',
            teach: {
              title: 'Not equal operator !=',
              explanation: '!= means "not equal to". Returns True when values are different.',
              example: { code: 'print(5 != 3)  # True\nprint(5 != 5)  # False', output: 'True\nFalse' },
              highlight: 'Think of ! as "not". != means "not equal".',
            },
            question: 'What operator checks if two values are NOT equal?',
            code: 'print(5 ___ 3)  # should print True',
            correct: '!=',
            explanation: '!= means "not equal to". 5 != 3 is True.',
          },
          {
            id: 'u2-l3-e5',
            type: 'true_false',
            teach: {
              title: 'Truthy and Falsy values',
              explanation: 'Every value in Python is either truthy or falsy. 0, empty strings, and None are falsy.',
              example: { code: 'print(bool(0))    # False\nprint(bool(1))    # True\nprint(bool(""))   # False\nprint(bool("hi")) # True', output: 'False\nTrue\nFalse\nTrue' },
              highlight: 'You can use if my_list: instead of if len(my_list) > 0:',
            },
            question: 'bool(0) returns False in Python.',
            correct: true,
            explanation: '0 is "falsy". bool(0) = False, bool(1) = True.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-3',
    title: 'Decisions',
    description: 'Making your code choose',
    icon: '🔀',
    color: '#f59e0b',
    lessons: [
      {
        id: 'u3-l1',
        title: 'If Statements',
        xpReward: 25,
        intro: {
          title: 'Your code can make decisions 🤔',
          summary: 'if statements let your code do different things depending on conditions.',
          concepts: [
            { label: 'Basic if', code: 'age = 20\nif age >= 18:\n    print("Adult")', output: 'Adult' },
            { label: 'if/elif/else', code: 'score = 75\nif score >= 90:\n    print("A")\nelif score >= 70:\n    print("B")\nelse:\n    print("C")', output: 'B' },
          ],
          tip: '💡 Indentation matters! Code inside an if block MUST be indented (4 spaces or Tab).',
        },
        summary: {
          title: 'if/elif/else — Decision making',
          points: [
            'if runs code only when condition is True',
            'else runs when the if condition is False',
            'elif checks another condition',
            'Conditions end with a colon :',
            'Code inside must be indented',
          ],
          cheatsheet: [
            { code: 'if x > 0:', desc: 'Basic condition' },
            { code: 'elif x == 0:', desc: 'Additional check' },
            { code: 'else:', desc: 'Fallback' },
          ],
        },
        exercises: [
          {
            id: 'u3-l1-e1',
            type: 'output_prediction',
            teach: {
              title: 'How if works',
              explanation: 'If the condition is True, Python runs the indented block. If False, it skips it.',
              example: { code: 'temp = 30\nif temp > 25:\n    print("Hot!")', output: 'Hot!' },
              highlight: 'Only the indented code is conditional.',
            },
            question: 'What will this print?\n\nx = 10\nif x > 5:\n    print("big")',
            options: ['big', 'nothing', 'True', 'Error'],
            correct: 0,
            explanation: 'x is 10, which IS greater than 5, so "big" gets printed.',
          },
          {
            id: 'u3-l1-e2',
            type: 'multiple_choice',
            teach: {
              title: 'if statement syntax',
              explanation: 'The syntax is: if keyword, condition, colon. The body is indented.',
              example: { code: 'if condition:\n    do_something()', output: '(runs if condition is True)' },
              highlight: 'The colon : at the end is required!',
            },
            question: 'What is the correct syntax for an if statement?',
            options: ['if x > 5 then:', 'if (x > 5):', 'if x > 5:', 'if x > 5 {'],
            correct: 2,
            explanation: 'Python if statements end with a colon : and use indentation.',
          },
          {
            id: 'u3-l1-e3',
            type: 'fill_blank',
            teach: {
              title: 'The else clause',
              explanation: 'else is the "otherwise" block — it runs when the if condition is False.',
              example: { code: 'if password == "secret":\n    print("Welcome!")\nelse:\n    print("Wrong password")', output: 'Wrong password' },
              highlight: 'else never has a condition. It\'s always the fallback.',
            },
            question: 'Complete the else clause:',
            code: 'if x > 0:\n    print("positive")\n___:\n    print("not positive")',
            correct: 'else',
            explanation: 'else runs when the if condition is False.',
          },
          {
            id: 'u3-l1-e4',
            type: 'spot_bug',
            teach: {
              title: 'The missing colon',
              explanation: 'Every if, elif, else line must end with a colon :',
              example: { code: '# Bug:\nif x == 5\n    print("five")\n\n# Fixed:\nif x == 5:\n    print("five")', output: 'SyntaxError!\nfive' },
              highlight: 'SyntaxError on an if line almost always means a missing colon.',
            },
            question: 'Find the bug:\n\nx = 5\nif x == 5\n    print("five")',
            options: ['Missing colon after if condition', 'Wrong indentation', 'Should use = not ==', 'No bug'],
            correct: 0,
            explanation: 'If statements need a colon : at the end of the condition line.',
          },
          {
            id: 'u3-l1-e5',
            type: 'output_prediction',
            teach: {
              title: 'if / elif / else chain',
              explanation: 'Python checks each condition in order and runs only the FIRST True one.',
              example: { code: 'grade = 85\nif grade >= 90:\n    print("A")\nelif grade >= 80:\n    print("B")\nelse:\n    print("C")', output: 'B' },
              highlight: 'Only ONE block runs — the first True condition wins.',
            },
            question: 'What will this print?\n\nscore = 75\nif score >= 90:\n    print("A")\nelif score >= 70:\n    print("B")\nelse:\n    print("C")',
            options: ['A', 'B', 'C', 'B and C'],
            correct: 1,
            explanation: '75 is not >= 90, but IS >= 70, so elif runs and prints "B".',
          },
        ],
      },
      {
        id: 'u3-l2',
        title: 'Logic Operators',
        xpReward: 25,
        intro: {
          title: 'Combining conditions 🔗',
          summary: 'Logic operators let you combine multiple conditions. and, or, not are the three logic operators.',
          concepts: [
            { label: 'and', code: 'x = 5\nif x > 0 and x < 10:\n    print("single digit")', output: 'single digit' },
            { label: 'or', code: 'day = "Saturday"\nif day == "Saturday" or day == "Sunday":\n    print("Weekend!")', output: 'Weekend!' },
            { label: 'not', code: 'raining = False\nif not raining:\n    print("Go outside!")', output: 'Go outside!' },
          ],
          tip: '💡 and needs BOTH true. or needs just ONE true. not flips True/False.',
        },
        summary: {
          title: 'Logic operators — and, or, not',
          points: [
            'and: True only if BOTH conditions are True',
            'or: True if AT LEAST ONE condition is True',
            'not: flips True to False and vice versa',
            'You can chain multiple: x > 0 and x < 10 and x != 5',
          ],
          cheatsheet: [
            { code: 'x > 0 and x < 10', desc: 'Both must be true' },
            { code: 'x < 0 or x > 100', desc: 'Either can be true' },
            { code: 'not is_done', desc: 'Flip the boolean' },
          ],
        },
        exercises: [
          {
            id: 'u3-l2-e1',
            type: 'output_prediction',
            teach: {
              title: 'The and operator',
              explanation: 'and returns True ONLY when BOTH sides are True.',
              example: { code: 'print(True and True)   # True\nprint(True and False)  # False', output: 'True\nFalse' },
              highlight: 'and is strict — both sides must be True.',
            },
            question: 'What will this print?\n\nprint(True and False)',
            options: ['True', 'False', 'Error', 'TrueFalse'],
            correct: 1,
            explanation: 'and returns True only if BOTH sides are True.',
          },
          {
            id: 'u3-l2-e2',
            type: 'output_prediction',
            teach: {
              title: 'The or operator',
              explanation: 'or returns True when AT LEAST ONE side is True.',
              example: { code: 'print(True or False)   # True\nprint(False or False)  # False', output: 'True\nFalse' },
              highlight: 'or is generous — just ONE True is enough.',
            },
            question: 'What will this print?\n\nprint(True or False)',
            options: ['True', 'False', 'Error', 'TrueOrFalse'],
            correct: 0,
            explanation: 'or returns True if AT LEAST ONE side is True.',
          },
          {
            id: 'u3-l2-e3',
            type: 'fill_blank',
            teach: {
              title: 'Using and in real conditions',
              explanation: 'and is perfect when you need multiple conditions to ALL be true.',
              example: { code: 'temp = 22\nif temp >= 18 and temp <= 28:\n    print("Perfect weather!")', output: 'Perfect weather!' },
              highlight: 'Much cleaner than nested ifs.',
            },
            question: 'Complete using the correct logic operator:',
            code: 'age = 20\nif age >= 18 ___ age < 65:\n    print("Working age")',
            correct: 'and',
            explanation: 'We want BOTH conditions true, so use and.',
          },
          {
            id: 'u3-l2-e4',
            type: 'output_prediction',
            teach: {
              title: 'The not operator',
              explanation: 'not flips a boolean. True becomes False, False becomes True.',
              example: { code: 'print(not True)   # False\nprint(not False)  # True', output: 'False\nTrue' },
              highlight: 'not logged_in reads naturally: "if NOT logged in".',
            },
            question: 'What will this print?\n\nprint(not True)',
            options: ['True', 'False', 'not True', 'Error'],
            correct: 1,
            explanation: 'not flips a boolean. not True = False.',
          },
          {
            id: 'u3-l2-e5',
            type: 'true_false',
            teach: {
              title: 'Combining operators',
              explanation: 'You can combine and, or, not in complex conditions.',
              example: { code: 'x = 5\nprint(x > 3 and x < 10)  # True', output: 'True' },
              highlight: 'Use parentheses to make complex conditions clear.',
            },
            question: 'x = 5\nThe expression (x > 3 and x < 10) evaluates to True.',
            correct: true,
            explanation: '5 > 3 is True AND 5 < 10 is True. Both True, so result is True.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-4',
    title: 'Loops',
    description: 'Repeat yourself (efficiently)',
    icon: '🔁',
    color: '#f87171',
    lessons: [
      {
        id: 'u4-l1',
        title: 'For Loops',
        xpReward: 30,
        intro: {
          title: 'Do things repeatedly 🔄',
          summary: 'Loops let you repeat code. A for loop runs a block of code once for each item in a sequence.',
          concepts: [
            { label: 'Loop with range', code: 'for i in range(3):\n    print(i)', output: '0\n1\n2' },
            { label: 'Loop over a string', code: 'for char in "cat":\n    print(char)', output: 'c\na\nt' },
          ],
          tip: '💡 The variable after for takes a new value each iteration. You can name it anything!',
        },
        summary: {
          title: 'for loops — Iterating over sequences',
          points: [
            'for x in sequence: runs once per item',
            'range(n) generates 0 to n-1',
            'range(start, stop) from start to stop-1',
            'range(start, stop, step) counts by step',
            'break exits loop early, continue skips to next',
          ],
          cheatsheet: [
            { code: 'range(5)      → 0,1,2,3,4', desc: 'Five iterations' },
            { code: 'range(1, 6)   → 1,2,3,4,5', desc: 'Custom start' },
            { code: 'range(0,10,2) → 0,2,4,6,8', desc: 'Step by 2' },
          ],
        },
        exercises: [
          {
            id: 'u4-l1-e1',
            type: 'output_prediction',
            teach: {
              title: 'range() and counting',
              explanation: 'range(n) generates numbers from 0 up to (not including) n.',
              example: { code: 'for i in range(4):\n    print(i)\n# values: 0, 1, 2, 3', output: '0\n1\n2\n3' },
              highlight: 'range(3) gives 0, 1, 2 — THREE numbers starting from 0.',
            },
            question: 'How many times will "hi" print?\n\nfor i in range(3):\n    print("hi")',
            options: ['2 times', '3 times', '4 times', 'Once'],
            correct: 1,
            explanation: 'range(3) generates [0, 1, 2] — three numbers, so the loop runs 3 times.',
          },
          {
            id: 'u4-l1-e2',
            type: 'output_prediction',
            teach: {
              title: 'Looping over strings',
              explanation: 'A for loop works on any sequence — including strings!',
              example: { code: 'for letter in "hi":\n    print(letter)', output: 'h\ni' },
              highlight: 'Any iterable works: strings, lists, ranges.',
            },
            question: 'What will this print?\n\nfor char in "cat":\n    print(char)',
            options: ['cat', 'c a t (on separate lines)', 'c-a-t', 'Error'],
            correct: 1,
            explanation: 'You can loop over a string! Each iteration gives you one character.',
          },
          {
            id: 'u4-l1-e3',
            type: 'fill_blank',
            teach: {
              title: 'range() with a start value',
              explanation: 'range(start, stop) counts from start up to (not including) stop.',
              example: { code: 'for i in range(1, 5):\n    print(i)\n# Prints: 1, 2, 3, 4', output: '1\n2\n3\n4' },
              highlight: 'The stop number is EXCLUSIVE — not included.',
            },
            question: 'Complete to loop from 1 to 5 inclusive:',
            code: 'for i in range(___, 6):\n    print(i)',
            correct: '1',
            explanation: 'range(1, 6) generates 1, 2, 3, 4, 5.',
          },
          {
            id: 'u4-l1-e4',
            type: 'multiple_choice',
            teach: {
              title: 'range() with step',
              explanation: 'range(start, stop, step) controls how much to add each time.',
              example: { code: 'for i in range(0, 10, 2):\n    print(i)\n# 0, 2, 4, 6, 8', output: '0\n2\n4\n6\n8' },
              highlight: 'Negative step counts backwards! range(5, 0, -1) = 5, 4, 3, 2, 1',
            },
            question: 'What does range(0, 10, 2) generate?',
            options: ['0 to 10', '0, 2, 4, 6, 8', '2, 4, 6, 8, 10', '0, 2, 4, 6, 8, 10'],
            correct: 1,
            explanation: 'Step of 2 means count by 2s. Stop (10) is excluded.',
          },
          {
            id: 'u4-l1-e5',
            type: 'true_false',
            teach: {
              title: 'The loop variable is flexible',
              explanation: 'The loop variable can be named anything. Use _ if you don\'t need it.',
              example: { code: 'for _ in range(3):\n    print("hello")  # _ = "unused"', output: 'hello\nhello\nhello' },
              highlight: 'Using _ is a convention meaning "I don\'t need this value".',
            },
            question: 'for loops in Python require a counter variable like i.',
            correct: false,
            explanation: 'You can loop over any iterable. You can even use _ if you don\'t need the variable.',
          },
        ],
      },
      {
        id: 'u4-l2',
        title: 'While Loops',
        xpReward: 30,
        intro: {
          title: 'Loop until something changes ⏳',
          summary: 'while loops keep running as long as a condition is True. Use them when you don\'t know how many times to repeat.',
          concepts: [
            { label: 'Basic while', code: 'count = 0\nwhile count < 3:\n    print(count)\n    count += 1', output: '0\n1\n2' },
            { label: 'break', code: 'while True:\n    if done:\n        break', output: '(exits when done)' },
          ],
          tip: '💡 Always make sure your while loop can end! Forgetting to update the condition causes an infinite loop.',
        },
        summary: {
          title: 'while loops — Condition-based repetition',
          points: [
            'while condition: runs as long as condition is True',
            'Must update the condition variable or loops forever!',
            'break immediately exits the loop',
            'continue skips to the next iteration',
            'while True: with break is common for "loop until done"',
          ],
          cheatsheet: [
            { code: 'while x < 10:', desc: 'Loop until false' },
            { code: 'break', desc: 'Exit immediately' },
            { code: 'continue', desc: 'Skip to next' },
          ],
        },
        exercises: [
          {
            id: 'u4-l2-e1',
            type: 'output_prediction',
            teach: {
              title: 'How while loops work',
              explanation: 'A while loop checks its condition before each iteration. Repeats until condition is False.',
              example: { code: 'n = 1\nwhile n <= 3:\n    print(n)\n    n += 1', output: '1\n2\n3' },
              highlight: 'n += 1 means n = n + 1. Without this, the loop never ends!',
            },
            question: 'What will this print?\n\nx = 0\nwhile x < 3:\n    print(x)\n    x += 1',
            options: ['0 1 2', '1 2 3', '0 1 2 3', 'Infinite loop'],
            correct: 0,
            explanation: 'Starts at 0, prints 0, 1, 2. When x becomes 3, loop stops.',
          },
          {
            id: 'u4-l2-e2',
            type: 'fill_blank',
            teach: {
              title: 'The break statement',
              explanation: 'break immediately exits the loop — it\'s the emergency exit.',
              example: { code: 'for i in range(10):\n    if i == 5:\n        break\n    print(i)\n# Stops before 5', output: '0\n1\n2\n3\n4' },
              highlight: 'break is essential for while True: loops.',
            },
            question: 'What keyword exits a loop immediately?',
            code: 'while True:\n    x = input("quit? ")\n    if x == "yes":\n        ___',
            correct: 'break',
            explanation: 'break immediately exits the loop.',
          },
          {
            id: 'u4-l2-e3',
            type: 'spot_bug',
            teach: {
              title: 'The infinite loop bug',
              explanation: 'Forgetting to update the condition variable causes an infinite loop.',
              example: { code: '# Bug:\nx = 0\nwhile x < 5:\n    print(x)  # x never changes!\n\n# Fixed: add x += 1', output: '(infinite!)\n0\n1\n2\n3\n4' },
              highlight: 'If your program freezes, press Ctrl+C to stop it.',
            },
            question: 'Find the bug (infinite loop):\n\nx = 0\nwhile x < 5:\n    print(x)',
            options: ['x is never incremented', 'Wrong comparison operator', 'Missing colon', 'No bug'],
            correct: 0,
            explanation: 'x never changes, so x < 5 is always True — infinite loop!',
          },
          {
            id: 'u4-l2-e4',
            type: 'multiple_choice',
            teach: {
              title: 'The continue statement',
              explanation: 'continue skips the rest of the current loop body and jumps to the next iteration.',
              example: { code: 'for i in range(5):\n    if i == 2:\n        continue\n    print(i)\n# Skips 2', output: '0\n1\n3\n4' },
              highlight: 'break = exit. continue = skip this one, keep going.',
            },
            question: 'What does continue do inside a loop?',
            options: ['Exits the loop', 'Skips to next iteration', 'Pauses the loop', 'Restarts from beginning'],
            correct: 1,
            explanation: 'continue skips the rest of the current iteration.',
          },
          {
            id: 'u4-l2-e5',
            type: 'true_false',
            teach: {
              title: 'for vs while — when to use each',
              explanation: 'Use for when you know the count. Use while when you loop until something changes.',
              example: { code: '# for: known count\nfor i in range(10):\n    process(i)\n\n# while: unknown\nwhile not game_over:\n    play_turn()', output: '(10 times)\n(until done)' },
              highlight: 'Most loops are for loops. Use while for unpredictable repetition.',
            },
            question: 'A while loop is better than a for loop when you don\'t know in advance how many times to repeat.',
            correct: true,
            explanation: 'Use for for known counts. Use while when the stopping condition changes dynamically.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-5',
    title: 'Functions',
    description: 'Write once, use forever',
    icon: '⚙️',
    color: '#60a5fa',
    lessons: [
      {
        id: 'u5-l1',
        title: 'Defining Functions',
        xpReward: 30,
        intro: {
          title: 'Reusable blocks of code ♻️',
          summary: 'Functions let you name a block of code and call it anywhere. Write it once, use it many times.',
          concepts: [
            { label: 'Define + call', code: 'def greet():\n    print("Hello!")\n\ngreet()', output: 'Hello!' },
            { label: 'With parameters', code: 'def greet(name):\n    print("Hello", name)\n\ngreet("Alex")', output: 'Hello Alex' },
            { label: 'With return', code: 'def double(n):\n    return n * 2\n\nprint(double(5))', output: '10' },
          ],
          tip: '💡 Good functions do ONE thing and do it well.',
        },
        summary: {
          title: 'Functions — define, call, return',
          points: [
            'def keyword defines a function',
            'Code inside only runs when you CALL the function',
            'Parameters are inputs to the function',
            'return sends a value back to the caller',
            'Functions without return give back None',
          ],
          cheatsheet: [
            { code: 'def name():', desc: 'Define a function' },
            { code: 'def name(x, y):', desc: 'With parameters' },
            { code: 'return value', desc: 'Send value back' },
          ],
        },
        exercises: [
          {
            id: 'u5-l1-e1',
            type: 'fill_blank',
            teach: {
              title: 'The def keyword',
              explanation: 'def is short for "define". Use it to create a new function.',
              example: { code: 'def say_hello():\n    print("Hello!")', output: '(defines function)' },
              highlight: 'def, like if and while, needs a colon at the end.',
            },
            question: 'Complete the keyword to define a function:',
            code: '___ greet():\n    print("Hello!")',
            correct: 'def',
            explanation: 'def is the keyword to define a function.',
          },
          {
            id: 'u5-l1-e2',
            type: 'multiple_choice',
            teach: {
              title: 'Define vs call',
              explanation: 'Defining creates the function. Calling actually runs it.',
              example: { code: 'def make_coffee():\n    print("Brewing...")\n\n# Nothing happens yet!\nmake_coffee()  # NOW it runs', output: 'Brewing...' },
              highlight: 'Think of def as writing a recipe. Calling it is actually cooking.',
            },
            question: 'When does a function\'s code actually run?',
            options: ['When you define it', 'When you call it', 'At the start', 'Never automatically'],
            correct: 1,
            explanation: 'The code inside only runs when you CALL the function.',
          },
          {
            id: 'u5-l1-e3',
            type: 'output_prediction',
            teach: {
              title: 'Parameters and return',
              explanation: 'Parameters are inputs. return sends a value back.',
              example: { code: 'def square(n):\n    return n * n\n\nprint(square(4))  # 16', output: '16' },
              highlight: 'The return value replaces the function call. square(4) literally becomes 16.',
            },
            question: 'What will this print?\n\ndef double(n):\n    return n * 2\n\nprint(double(5))',
            options: ['n * 2', '10', '5', 'double(5)'],
            correct: 1,
            explanation: 'double(5) returns 5 * 2 = 10.',
          },
          {
            id: 'u5-l1-e4',
            type: 'spot_bug',
            teach: {
              title: 'Function definition syntax',
              explanation: 'The def line must end with a colon.',
              example: { code: '# Bug:\ndef greet()\n    print("hi")\n\n# Fixed:\ndef greet():\n    print("hi")', output: 'SyntaxError!\nhi' },
              highlight: 'SyntaxError on a def line usually means missing colon.',
            },
            question: 'Find the bug:\n\ndef add(a, b)\n    return a + b',
            options: ['Missing colon after def line', 'return should be print', 'Missing parentheses', 'No bug'],
            correct: 0,
            explanation: 'The function definition line must end with a colon :',
          },
          {
            id: 'u5-l1-e5',
            type: 'true_false',
            teach: {
              title: 'Functions return None by default',
              explanation: 'Without return, Python returns None (which means "nothing").',
              example: { code: 'def say_hi():\n    print("hi")\n\nresult = say_hi()\nprint(result)  # None', output: 'hi\nNone' },
              highlight: 'None is not an error — it means no return value.',
            },
            question: 'A function without a return statement returns None.',
            correct: true,
            explanation: 'Without return, Python automatically returns None.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-6',
    title: 'Lists',
    description: 'Collections of things',
    icon: '📋',
    color: '#c084fc',
    lessons: [
      {
        id: 'u6-l1',
        title: 'List Basics',
        xpReward: 35,
        intro: {
          title: 'Storing multiple values 📦📦📦',
          summary: 'A list stores multiple values in one variable. Instead of name1, name2, name3 — one names list.',
          concepts: [
            { label: 'Create & access', code: 'fruits = ["apple", "banana", "cherry"]\nprint(fruits[0])   # apple\nprint(fruits[-1])  # cherry', output: 'apple\ncherry' },
            { label: 'Modify', code: 'nums = [1, 2, 3]\nnums.append(4)\nprint(nums)', output: '[1, 2, 3, 4]' },
          ],
          tip: '💡 Lists are ordered and mutable. Indexing starts at 0!',
        },
        summary: {
          title: 'Lists — Ordered collections',
          points: [
            'Lists use square brackets: [1, 2, 3]',
            'Index starts at 0. Last item at index -1',
            '.append(x) adds x to the end',
            '.remove(x) removes first occurrence of x',
            'len(list) gives number of items',
          ],
          cheatsheet: [
            { code: 'list[0]', desc: 'First item' },
            { code: 'list[-1]', desc: 'Last item' },
            { code: 'list.append(x)', desc: 'Add to end' },
            { code: 'len(list)', desc: 'Count items' },
          ],
        },
        exercises: [
          {
            id: 'u6-l1-e1',
            type: 'output_prediction',
            teach: {
              title: 'List indexing starts at 0',
              explanation: 'Items are accessed by index starting at 0.',
              example: { code: 'colors = ["red", "green", "blue"]\nprint(colors[0])  # red\nprint(colors[2])  # blue', output: 'red\nblue' },
              highlight: 'Zero-based indexing applies to all sequences in Python.',
            },
            question: 'What will this print?\n\nfruits = ["apple", "banana", "cherry"]\nprint(fruits[1])',
            options: ['apple', 'banana', 'cherry', 'Error'],
            correct: 1,
            explanation: 'Index 1 is the second item: "banana".',
          },
          {
            id: 'u6-l1-e2',
            type: 'fill_blank',
            teach: {
              title: 'Adding to a list',
              explanation: '.append() adds one item to the END of the list.',
              example: { code: 'todos = []\ntodos.append("Buy milk")\nprint(todos)', output: "['Buy milk']" },
              highlight: '.append() modifies the list IN PLACE.',
            },
            question: 'Add an item to the end of a list:',
            code: 'numbers = [1, 2, 3]\nnumbers.___(4)',
            correct: 'append',
            explanation: '.append() adds an item to the END of a list.',
          },
          {
            id: 'u6-l1-e3',
            type: 'output_prediction',
            teach: {
              title: 'len() on lists',
              explanation: 'len() works on any sequence. For lists, it returns the number of items.',
              example: { code: 'scores = [95, 87, 73]\nprint(len(scores))  # 3', output: '3' },
              highlight: 'len() counts items, not the highest index.',
            },
            question: 'What will this print?\n\nnums = [10, 20, 30]\nprint(len(nums))',
            options: ['10', '30', '3', '60'],
            correct: 2,
            explanation: 'len() returns the number of items. There are 3.',
          },
          {
            id: 'u6-l1-e4',
            type: 'multiple_choice',
            teach: {
              title: 'Negative indexing',
              explanation: '-1 is the last item, -2 is second to last. Useful when you don\'t know the length!',
              example: { code: 'letters = ["a", "b", "c", "d"]\nprint(letters[-1])  # d\nprint(letters[-2])  # c', output: 'd\nc' },
              highlight: 'letters[-1] is the same as letters[len(letters)-1] but cleaner.',
            },
            question: 'How do you get the LAST item in any list?',
            options: ['list[last]', 'list[-1]', 'list[len-1]', 'list.last()'],
            correct: 1,
            explanation: '-1 always means the last item.',
          },
          {
            id: 'u6-l1-e5',
            type: 'true_false',
            teach: {
              title: 'Lists can hold mixed types',
              explanation: 'Python lists can contain any mix of types.',
              example: { code: 'mixed = [42, "hello", True, 3.14]\nprint(mixed[0])  # 42\nprint(mixed[1])  # hello', output: '42\nhello' },
              highlight: 'This flexibility is powerful but use carefully.',
            },
            question: 'A Python list can contain items of different types.',
            correct: true,
            explanation: 'Python lists are flexible! [1, "hello", True, 3.14] is totally valid.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-7',
    title: 'Dictionaries',
    description: 'Key-value powerhouses',
    icon: '📖',
    color: '#2dd4bf',
    lessons: [
      {
        id: 'u7-l1',
        title: 'Dict Basics',
        xpReward: 35,
        intro: {
          title: 'Data with labels 🏷️',
          summary: 'Dictionaries store data as key-value pairs. Use meaningful labels (keys) to access values.',
          concepts: [
            { label: 'Create & access', code: 'person = {"name": "Alex", "age": 25}\nprint(person["name"])', output: 'Alex' },
            { label: 'Add/update', code: 'person["email"] = "alex@x.com"\nprint(person["email"])', output: 'alex@x.com' },
          ],
          tip: '💡 Dictionaries are like real dictionaries — look up a word (key) to get a definition (value).',
        },
        summary: {
          title: 'Dictionaries — Key-value storage',
          points: [
            'Dicts use curly braces: {"key": value}',
            'Access values with dict["key"]',
            '.get("key") returns None if key missing (no error)',
            'Add new pairs: dict["new_key"] = value',
            'Keys must be unique',
          ],
          cheatsheet: [
            { code: 'd["key"]', desc: 'Access value' },
            { code: 'd.get("key")', desc: 'Safe access' },
            { code: 'd["key"] = val', desc: 'Add or update' },
          ],
        },
        exercises: [
          {
            id: 'u7-l1-e1',
            type: 'output_prediction',
            teach: {
              title: 'Accessing dict values',
              explanation: 'Use the key in square brackets to get the value.',
              example: { code: 'car = {"brand": "Toyota"}\nprint(car["brand"])', output: 'Toyota' },
              highlight: 'Keys are case-sensitive! "brand" and "Brand" are different.',
            },
            question: 'What will this print?\n\nperson = {"name": "Alex", "age": 25}\nprint(person["name"])',
            options: ['Alex', 'name', '25', 'Error'],
            correct: 0,
            explanation: '"name" key maps to "Alex".',
          },
          {
            id: 'u7-l1-e2',
            type: 'fill_blank',
            teach: {
              title: 'Adding key-value pairs',
              explanation: 'Assign to a new key to add it. Assign to an existing key to update it.',
              example: { code: 'profile = {"name": "Sam"}\nprofile["age"] = 30\nprint(profile)', output: "{'name': 'Sam', 'age': 30}" },
              highlight: 'Python automatically creates or updates.',
            },
            question: 'Add a new key-value pair to a dict:',
            code: 'car = {"color": "red"}\ncar[___] = "Toyota"',
            correct: '"brand"',
            explanation: 'Assign to a new key to add it.',
          },
          {
            id: 'u7-l1-e3',
            type: 'multiple_choice',
            teach: {
              title: '.get() for safe access',
              explanation: '[] raises a KeyError if key missing. .get() returns None instead.',
              example: { code: 'data = {"name": "Alex"}\nprint(data.get("age"))      # None\nprint(data.get("age", 0))   # 0', output: 'None\n0' },
              highlight: '.get("key", default) — second argument is the default.',
            },
            question: 'What does .get() do when a key doesn\'t exist?',
            options: ['Raises an error', 'Returns None instead of error', 'Creates the key', 'Returns False'],
            correct: 1,
            explanation: '.get() safely returns None instead of a KeyError.',
          },
          {
            id: 'u7-l1-e4',
            type: 'true_false',
            teach: {
              title: 'Keys must be unique',
              explanation: 'Duplicate keys overwrite the previous value.',
              example: { code: 'scores = {"Alice": 95, "Alice": 87}\nprint(scores)  # Alice: 87 only', output: "{'Alice': 87}" },
              highlight: 'No duplicate keys — the last value wins.',
            },
            question: 'Dictionary keys must be unique.',
            correct: true,
            explanation: 'Each key can only appear once.',
          },
          {
            id: 'u7-l1-e5',
            type: 'spot_bug',
            teach: {
              title: 'Keys need quotes',
              explanation: 'String keys must be in quotes. Without quotes, Python thinks it\'s a variable.',
              example: { code: '# Bug:\nd = {name: "Alex"}  # NameError!\n\n# Fixed:\nd = {"name": "Alex"}', output: 'NameError!\nOK' },
              highlight: 'Keys are usually strings in quotes.',
            },
            question: 'Find the bug:\n\nstudent = {name: "Sam", "grade": "A"}',
            options: ['name key is missing quotes', 'Missing parentheses', 'Grade should be a number', 'No bug'],
            correct: 0,
            explanation: 'String keys need quotes: {"name": "Sam"}.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-8',
    title: 'Errors & Files',
    description: 'Handle the unexpected',
    icon: '🛡️',
    color: '#fb923c',
    lessons: [
      {
        id: 'u8-l1',
        title: 'Try & Except',
        xpReward: 40,
        intro: {
          title: 'Handling errors gracefully 🛡️',
          summary: 'try/except lets you catch errors instead of crashing. This is what separates fragile code from real apps.',
          concepts: [
            { label: 'Basic try/except', code: 'try:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print("Can\'t divide by zero!")', output: "Can't divide by zero!" },
            { label: 'Catch ValueError', code: 'try:\n    num = int("abc")\nexcept ValueError:\n    print("Not a number!")', output: 'Not a number!' },
          ],
          tip: '💡 Catch SPECIFIC errors (ValueError, TypeError) rather than all errors — it makes debugging easier.',
        },
        summary: {
          title: 'try/except — Error handling',
          points: [
            'try: contains the code that might fail',
            'except ErrorType: handles that specific error',
            'Multiple except blocks are allowed',
            'else: runs if no error occurred',
            'finally: always runs, error or not',
          ],
          cheatsheet: [
            { code: 'try:', desc: 'Risky code here' },
            { code: 'except ValueError:', desc: 'Catch specific error' },
            { code: 'finally:', desc: 'Always runs' },
          ],
        },
        exercises: [
          {
            id: 'u8-l1-e1',
            type: 'multiple_choice',
            teach: {
              title: 'Why error handling matters',
              explanation: 'Without try/except, any error crashes your program. With it, you handle problems gracefully.',
              example: { code: '# Without:\nresult = int("abc")  # CRASH!\n\n# With:\ntry:\n    result = int("abc")\nexcept ValueError:\n    result = 0\nprint("Done")', output: 'CRASH!\nDone' },
              highlight: 'Error handling is essential for programs that take user input.',
            },
            question: 'What does try/except do?',
            options: ['Speeds up code', 'Catches and handles errors gracefully', 'Tests your code', 'Tries multiple values'],
            correct: 1,
            explanation: 'try/except lets you catch errors instead of crashing.',
          },
          {
            id: 'u8-l1-e2',
            type: 'fill_blank',
            teach: {
              title: 'try/except syntax',
              explanation: 'try first, then except. try contains the risky code.',
              example: { code: 'try:\n    age = int(input("Age: "))\nexcept ValueError:\n    print("Please enter a number!")', output: '(handles bad input)' },
              highlight: '"attempt this, and if it fails, do this instead".',
            },
            question: 'Complete the error handling:',
            code: '___:\n    result = 10 / 0\nexcept:\n    print("Cannot divide by zero")',
            correct: 'try',
            explanation: 'try contains the risky code. except handles errors.',
          },
          {
            id: 'u8-l1-e3',
            type: 'output_prediction',
            teach: {
              title: 'Catching specific errors',
              explanation: 'Different errors have different types. Catch specific ones for better control.',
              example: { code: 'try:\n    x = int("hello")\nexcept ValueError:\n    print("Not valid")', output: 'Not valid' },
              highlight: 'Specific is better than catching all errors.',
            },
            question: 'What will this print?\n\ntry:\n    print(int("abc"))\nexcept ValueError:\n    print("Bad number!")',
            options: ['abc', 'Error', 'Bad number!', 'Nothing'],
            correct: 2,
            explanation: 'int("abc") raises a ValueError. The except block catches it.',
          },
          {
            id: 'u8-l1-e4',
            type: 'true_false',
            teach: {
              title: 'Multiple except blocks',
              explanation: 'Stack multiple except blocks to handle different error types.',
              example: { code: 'try:\n    do_thing()\nexcept KeyError:\n    print("Key missing")\nexcept TypeError:\n    print("Wrong type")', output: '(handles both errors)' },
              highlight: 'Python checks each except in order and runs the first match.',
            },
            question: 'You can have multiple except blocks for different error types.',
            correct: true,
            explanation: 'Yes! Stack them to handle different errors differently.',
          },
          {
            id: 'u8-l1-e5',
            type: 'spot_bug',
            teach: {
              title: 'try always comes first',
              explanation: 'The order is always try THEN except. You can\'t catch before you try!',
              example: { code: '# Bug:\nexcept:\n    print("error")\ntry:\n    risky()\n\n# Fixed:\ntry:\n    risky()\nexcept:\n    print("error")', output: 'SyntaxError!\nOK' },
              highlight: '"I\'ll TRY this, and if it fails, EXCEPT I\'ll do this."',
            },
            question: 'Find the bug:\n\nexcept:\n    print("error")\ntry:\n    risky_code()',
            options: ['try must come before except', 'Missing error type', 'risky_code is not defined', 'No bug'],
            correct: 0,
            explanation: 'try ALWAYS comes first, then except.',
          },
        ],
      },
    ],
  },
]

export function getAllLessons() {
  return CURRICULUM.flatMap(unit =>
    unit.lessons.map(lesson => ({ ...lesson, unitId: unit.id, unitTitle: unit.title, unitColor: unit.color }))
  )
}

export function getLessonById(lessonId) {
  for (const unit of CURRICULUM) {
    for (const lesson of unit.lessons) {
      if (lesson.id === lessonId) {
        return { ...lesson, unitId: unit.id, unitTitle: unit.title, unitColor: unit.color }
      }
    }
  }
  return null
}

export function getTotalLessons() {
  return CURRICULUM.reduce((acc, unit) => acc + unit.lessons.length, 0)
}